# Generated by Django 3.2.9 on 2021-11-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211112_2318'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('collection1')
        """, """
            DEELETE FROM store_collection
            WHERE title='collection1'
         """)
    ]
