# Generated by Django 3.2.9 on 2021-11-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211114_2104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costumer',
            new_name='Custumer',
        ),
        migrations.RemoveIndex(
            model_name='custumer',
            name='store_costu_last_na_66ca2f_idx',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='costumer',
            new_name='custumer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='costumer',
            new_name='custumer',
        ),
        migrations.AddIndex(
            model_name='custumer',
            index=models.Index(fields=['last_name', 'first_name'], name='store_custu_last_na_c23e59_idx'),
        ),
        migrations.AlterModelTable(
            name='custumer',
            table='store_custumers',
        ),
    ]
