# Generated by Django 3.2.9 on 2021-11-14 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20211114_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custumer',
            old_name='memebership',
            new_name='membership',
        ),
    ]
