# Generated by Django 3.2.9 on 2021-11-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggeditem',
            old_name='contetn_type',
            new_name='content_type',
        ),
    ]
